/**
 * Message Codec
 *
 * Handles encoding and decoding of VTP consensus messages:
 * 1. Serialize MessageBody to Protobuf binary
 * 2. Sign with Ed25519 (using the sender's secret key)
 * 3. Wrap in SignedMessage envelope
 * 4. Encode to final Protobuf binary for transmission
 *
 * On receive:
 * 1. Decode SignedMessage envelope from binary
 * 2. Verify Ed25519 signature against sender_pubkey
 * 3. Check timestamp freshness (±30s window)
 * 4. Decode inner MessageBody
 * 5. Return typed DecodedMessage
 *
 * Uses protobufjs static code generation for tree-shakeable, type-safe
 * encode/decode. Falls back to dynamic loading if static code is unavailable.
 *
 * @example
 * ```typescript
 * const codec = new MessageCodec(keypair);
 *
 * // Encode
 * const encoded = codec.encode({
 *   type: 'checkpoint',
 *   step: 1000,
 *   vdfState: new Uint8Array(32),
 *   vrfProof: new Uint8Array(80),
 * });
 *
 * // Decode (with signature verification)
 * const decoded = codec.decode(encoded);
 * ```
 */

import type { DecodedMessage, MessageType, MessagePayload, SigningKeyPair } from './types';
import type { CryptoProvider } from '$lib/consensus/crypto-provider';

// ─── Protobuf Static Imports ──────────────────────────────────────
// The generated code is imported dynamically at init time to avoid
// hard failures if the proto hasn't been generated yet.

let vtpProto: typeof import('../../../proto/vtp_messages') | null = null;

/**
 * Initialize the codec with the generated Protobuf module.
 * Must be called once before encode/decode.
 */
export async function initCodec(): Promise<void> {
  try {
    vtpProto = await import('../../../proto/vtp_messages.js');
  } catch {
    console.warn(
      '[MessageCodec] Protobuf module not found. Run `cd proto && npm run generate` first.'
    );
    throw new Error('Protobuf module not available');
  }
}

/** Timestamp tolerance for replay protection (±30 seconds). */
const TIMESTAMP_TOLERANCE_MS = 30_000;

/** Ed25519 signature length. */
const SIGNATURE_LENGTH = 64;

/** Ed25519 public key length. */
const PUBKEY_LENGTH = 32;

// ─── Message Type Mapping ─────────────────────────────────────────

/** Map from protobuf oneof field name (camelCase, as generated by protobufjs) to our MessageType. */
const FIELD_TO_TYPE: Record<string, MessageType> = {
  ping: 'ping',
  pong: 'pong',
  checkpoint: 'checkpoint',
  winner: 'winner',
  peerInfo: 'peer-discovery',
  vdfProgress: 'vdf-progress',
  consensusProposal: 'consensus-proposal',
  consensusVote: 'consensus-vote',
  newRound: 'new-round'
};

// ─── Codec Class ──────────────────────────────────────────────────

export class MessageCodec {
  private keypair: SigningKeyPair;
  private crypto: CryptoProvider;

  constructor(keypair: SigningKeyPair, crypto: CryptoProvider) {
    this.keypair = keypair;
    this.crypto = crypto;
  }

  /**
   * Encode a consensus message into a signed Protobuf binary.
   *
   * @param payload - The message payload to encode.
   * @returns Binary data ready for transmission over DataChannel.
   */
  encode(payload: MessagePayload): Uint8Array {
    if (!vtpProto) {
      throw new Error('Codec not initialized — call initCodec() first');
    }

    // 1. Build the inner MessageBody
    const body = this.buildMessageBody(payload);
    const bodyBytes = vtpProto.vtp.MessageBody.encode(body).finish();

    // 2. Sign the body bytes
    const signature = this.sign(bodyBytes);

    // 3. Build the SignedMessage envelope
    const envelope = {
      payload: bodyBytes,
      senderPubkey: this.keypair.publicKey,
      signature,
      timestamp: Date.now()
    };

    // 4. Encode the envelope (convert Buffer to Uint8Array for cross-env compat)
    const encoded = vtpProto.vtp.SignedMessage.encode(envelope as Record<string, unknown>).finish();
    return new Uint8Array(encoded);
  }

  /**
   * Decode and verify a signed Protobuf message.
   *
   * @param data - Raw binary data received from a DataChannel.
   * @returns Decoded message with verified sender, or null if invalid.
   */
  decode(data: ArrayBuffer | Uint8Array): DecodedMessage | null {
    if (!vtpProto) {
      throw new Error('Codec not initialized — call initCodec() first');
    }

    try {
      const bytes = data instanceof Uint8Array ? data : new Uint8Array(data);

      // 1. Decode the envelope
      const envelope = vtpProto.vtp.SignedMessage.decode(bytes);

      // 2. Verify timestamp freshness
      const now = Date.now();
      const msgTime = Number(envelope.timestamp);
      if (Math.abs(now - msgTime) > TIMESTAMP_TOLERANCE_MS) {
        console.warn('[MessageCodec] Message rejected: timestamp out of window');
        return null;
      }

      // 3. Verify signature
      if (!this.verify(envelope.payload, envelope.signature, envelope.senderPubkey)) {
        console.warn('[MessageCodec] Message rejected: invalid signature');
        return null;
      }

      // 4. Decode the inner body
      const body = vtpProto.vtp.MessageBody.decode(envelope.payload) as unknown as Record<
        string,
        unknown
      >;
      const payload = this.extractPayload(body);

      if (!payload) {
        console.warn('[MessageCodec] Message rejected: unknown body type');
        return null;
      }

      return {
        type: payload.type,
        senderPubkey: envelope.senderPubkey,
        timestamp: msgTime,
        payload
      };
    } catch (err) {
      console.warn('[MessageCodec] Decode error:', err);
      return null;
    }
  }

  // ─── Private: Protobuf Mapping ──────────────────────────────────

  /** Build a Protobuf MessageBody from our MessagePayload. */
  private buildMessageBody(payload: MessagePayload): Record<string, unknown> {
    switch (payload.type) {
      case 'ping':
        return { ping: { nonce: payload.nonce } };
      case 'pong':
        return { pong: { nonce: payload.nonce } };
      case 'checkpoint':
        return {
          checkpoint: {
            step: payload.step,
            vdfState: payload.vdfState,
            vrfProof: payload.vrfProof,
            senderPubkey: payload.senderPubkey
          }
        };
      case 'winner':
        return {
          winner: {
            step: payload.step,
            vrfProof: payload.vrfProof,
            senderPubkey: payload.senderPubkey
          }
        };
      case 'peer-discovery':
        return {
          peerInfo: {
            nodeId: payload.nodeId,
            publicKey: payload.publicKey,
            addresses: payload.addresses
          }
        };
      case 'vdf-progress':
        return {
          vdfProgress: {
            step: payload.step,
            speed: payload.speed
          }
        };
      case 'consensus-proposal':
        return {
          consensusProposal: {
            round: payload.round,
            vdfState: payload.vdfState,
            vrfProof: payload.vrfProof,
            blockHash: payload.blockHash,
            prevBlockHash: payload.prevBlockHash,
            timestamp: payload.timestamp
          }
        };
      case 'consensus-vote':
        return {
          consensusVote: {
            round: payload.round,
            phase: payload.phase === 'prevote' ? 0 : 1,
            blockHash: payload.blockHash ?? new Uint8Array(0),
            voterPubkey: payload.voterPubkey
          }
        };
      case 'new-round':
        return {
          newRound: {
            round: payload.round,
            seed: payload.seed,
            validators: payload.validators
          }
        };
    }
  }

  /** Extract our MessagePayload from a decoded Protobuf MessageBody. */
  private extractPayload(body: Record<string, unknown>): MessagePayload | null {
    // Find which oneof field is set
    for (const [field, type] of Object.entries(FIELD_TO_TYPE)) {
      if (body[field] !== undefined && body[field] !== null) {
        const inner = body[field] as Record<string, unknown>;
        return this.mapPayload(type, inner);
      }
    }
    return null;
  }

  /** Map a Protobuf inner message to our typed payload. */
  private mapPayload(type: MessageType, inner: Record<string, unknown>): MessagePayload {
    switch (type) {
      case 'ping':
        return { type: 'ping', nonce: Number(inner.nonce) };
      case 'pong':
        return { type: 'pong', nonce: Number(inner.nonce) };
      case 'checkpoint':
        return {
          type: 'checkpoint',
          step: Number(inner.step),
          vdfState: new Uint8Array(inner.vdfState as Uint8Array),
          vrfProof: new Uint8Array(inner.vrfProof as Uint8Array),
          senderPubkey: new Uint8Array(inner.senderPubkey as Uint8Array)
        };
      case 'winner':
        return {
          type: 'winner',
          step: Number(inner.step),
          vrfProof: new Uint8Array(inner.vrfProof as Uint8Array),
          senderPubkey: new Uint8Array(inner.senderPubkey as Uint8Array)
        };
      case 'peer-discovery':
        return {
          type: 'peer-discovery',
          nodeId: inner.nodeId as string,
          publicKey: new Uint8Array(inner.publicKey as Uint8Array),
          addresses: (inner.addresses as string[]) || []
        };
      case 'vdf-progress':
        return {
          type: 'vdf-progress',
          step: Number(inner.step),
          speed: Number(inner.speed)
        };
      case 'consensus-proposal':
        return {
          type: 'consensus-proposal',
          round: Number(inner.round),
          vdfState: new Uint8Array(inner.vdfState as Uint8Array),
          vrfProof: new Uint8Array(inner.vrfProof as Uint8Array),
          blockHash: new Uint8Array(inner.blockHash as Uint8Array),
          prevBlockHash: new Uint8Array(inner.prevBlockHash as Uint8Array),
          timestamp: Number(inner.timestamp)
        };
      case 'consensus-vote': {
        const rawHash = inner.blockHash as Uint8Array;
        return {
          type: 'consensus-vote',
          round: Number(inner.round),
          phase: inner.phase === 0 ? 'prevote' : 'precommit',
          blockHash: rawHash && rawHash.length > 0 ? new Uint8Array(rawHash) : null,
          voterPubkey: new Uint8Array(inner.voterPubkey as Uint8Array)
        };
      }
      case 'new-round':
        return {
          type: 'new-round',
          round: Number(inner.round),
          seed: new Uint8Array(inner.seed as Uint8Array),
          validators: (inner.validators as Uint8Array[]).map((v: Uint8Array) => new Uint8Array(v))
        };
    }
  }

  // ─── Private: Ed25519 Signing ───────────────────────────────────

  /**
   * Sign data with Ed25519 using the crypto provider.
   */
  private sign(data: Uint8Array): Uint8Array {
    return this.crypto.ed25519Sign(this.keypair.secretKey, data);
  }

  /**
   * Verify an Ed25519 signature using the crypto provider.
   */
  private verify(data: Uint8Array, signature: Uint8Array, publicKey: Uint8Array): boolean {
    if (signature.length !== SIGNATURE_LENGTH) return false;
    if (publicKey.length !== PUBKEY_LENGTH) return false;
    return this.crypto.ed25519Verify(publicKey, data, signature);
  }
}

// ─── Standalone Helpers ───────────────────────────────────────────

/**
 * Create a simple ping message payload.
 */
export function createPing(nonce: number): MessagePayload {
  return { type: 'ping', nonce };
}

/**
 * Create a pong response payload.
 */
export function createPong(nonce: number): MessagePayload {
  return { type: 'pong', nonce };
}

/**
 * Create a checkpoint announce payload.
 */
export function createCheckpoint(
  step: number,
  vdfState: Uint8Array,
  vrfProof: Uint8Array,
  senderPubkey: Uint8Array
): MessagePayload {
  return { type: 'checkpoint', step, vdfState, vrfProof, senderPubkey };
}

/**
 * Create a winner announce payload.
 */
export function createWinner(
  step: number,
  vrfProof: Uint8Array,
  senderPubkey: Uint8Array
): MessagePayload {
  return { type: 'winner', step, vrfProof, senderPubkey };
}

/**
 * Create a peer discovery payload.
 */
export function createPeerDiscovery(
  nodeId: string,
  publicKey: Uint8Array,
  addresses: string[] = []
): MessagePayload {
  return { type: 'peer-discovery', nodeId, publicKey, addresses };
}

/**
 * Create a VDF progress payload.
 */
export function createVdfProgress(step: number, speed: number): MessagePayload {
  return { type: 'vdf-progress', step, speed };
}

/**
 * Create a consensus proposal payload.
 */
export function createConsensusProposal(
  round: number,
  vdfState: Uint8Array,
  vrfProof: Uint8Array,
  blockHash: Uint8Array,
  prevBlockHash: Uint8Array,
  timestamp: number
): MessagePayload {
  return {
    type: 'consensus-proposal',
    round,
    vdfState,
    vrfProof,
    blockHash,
    prevBlockHash,
    timestamp
  };
}

/**
 * Create a consensus vote payload.
 */
export function createConsensusVote(
  round: number,
  phase: 'prevote' | 'precommit',
  blockHash: Uint8Array | null,
  voterPubkey: Uint8Array
): MessagePayload {
  return { type: 'consensus-vote', round, phase, blockHash, voterPubkey };
}

/**
 * Create a new round announcement payload.
 */
export function createNewRound(
  round: number,
  seed: Uint8Array,
  validators: Uint8Array[]
): MessagePayload {
  return { type: 'new-round', round, seed, validators };
}
